from __future__ import annotations

import inspect
import unittest

from cairn.dispatcher.prompting import load_prompt
from cairn.dispatcher.runtime.environments.base import EnvironmentHandle
from cairn.dispatcher.tasks import explore
from cairn.dispatcher.tasks.reports import (
    build_report_path,
    metadata_for_report,
    report_instruction,
    validate_report_written,
    write_autogenerated_report,
    write_failure_report,
)


class FakeEnvironment:
    id = "fake"
    backend = "ssh"

    def __init__(self) -> None:
        self.files: dict[str, str] = {}

    def write_text_file(self, handle, path, content) -> None:
        if not self.is_path_in_workspace(handle, path):
            raise RuntimeError("outside workspace")
        self.files[path] = content

    def exists(self, handle, path) -> bool:
        return path in self.files

    def is_path_in_workspace(self, handle, path) -> bool:
        return path == handle.workspace or path.startswith(handle.workspace.rstrip("/") + "/")


class CommandBlackboardV2ReportTests(unittest.TestCase):
    def setUp(self) -> None:
        self.handle = EnvironmentHandle(project_id="proj_001", target_name="ssh", workspace="/tmp/cairn/proj_001")

    def test_report_path_and_instruction(self) -> None:
        path = build_report_path(self.handle, "i001", "run_abc")

        self.assertEqual(path, "/tmp/cairn/proj_001/.cairn/reports/execution-i001-run_abc.md")
        self.assertIn(path, report_instruction(path))

    def test_validate_report_written_requires_file_inside_workspace(self) -> None:
        env = FakeEnvironment()
        path = build_report_path(self.handle, "i001", "run_abc")

        self.assertFalse(validate_report_written(env, self.handle, path))
        env.write_text_file(self.handle, path, "report")
        self.assertTrue(validate_report_written(env, self.handle, path))
        self.assertFalse(validate_report_written(env, self.handle, "/tmp/cairn/proj_0012/report.md"))

    def test_failure_report_and_metadata(self) -> None:
        env = FakeEnvironment()
        path = build_report_path(self.handle, "i001", "run_abc")

        write_failure_report(env, self.handle, path, intent_id="i001", worker="alpha", run_id="run_abc", reason="timeout")

        self.assertIn("timeout", env.files[path])
        self.assertEqual(
            metadata_for_report(path, "run_abc", "alpha", "i001", producing_run_log_id="run_log_123"),
            {
                "report_path": path,
                "report_run_id": "run_abc",
                "worker": "alpha",
                "intent_id": "i001",
                "provenance": {
                    "producing_intent_id": "i001",
                    "producing_run_log_id": "run_log_123",
                    "report_run_id": "run_abc",
                    "report_path": path,
                    "worker_name": "alpha",
                },
            },
        )

    def test_autogenerated_report_preserves_valid_worker_result(self) -> None:
        env = FakeEnvironment()
        path = build_report_path(self.handle, "i001", "run_abc")

        write_autogenerated_report(
            env,
            self.handle,
            path,
            intent_id="i001",
            worker="pi",
            run_id="run_abc",
            title="Create file",
            description="Created the requested empty file.",
            reason="worker_omitted_report",
        )

        self.assertIn("Created the requested empty file.", env.files[path])
        self.assertIn("Create file", env.files[path])
        self.assertIn("dispatcher_autogenerated", env.files[path])

    def test_reason_prompt_teaches_report_metadata(self) -> None:
        prompt = load_prompt("default", "reason.md")

        self.assertIn("metadata.report_path", prompt)
        self.assertIn("read the relevant report files", prompt)

    def test_conclude_prompt_allows_report_write(self) -> None:
        prompt = load_prompt("default", "explore_conclude.md")

        self.assertIn("create parent directories if needed", prompt)
        self.assertIn("writing the report file are the only allowed actions", prompt)
        self.assertNotIn("make any more tool calls", prompt)

    def test_explore_conclude_fallback_tolerates_missing_cancellation(self) -> None:
        source = inspect.getsource(explore._try_conclude_fallback)

        self.assertIn("cancellation: TaskCancellation | None", source)
        self.assertIn("cancellation is not None and cancellation.reason == \"conclude_requested\"", source)
        self.assertIn("cancellation is not None and cancellation.is_cancelled", source)

    def test_failure_release_marks_execution_failed_and_emits_diagnostic(self) -> None:
        class FakeClient:
            def __init__(self) -> None:
                self.events: list[dict] = []
                self.patches: list[dict] = []
                self.released: list[tuple[str, str, str]] = []

            def append_execution_events(self, execution_id, *, dispatcher_id=None, events=None):
                self.events.extend(events or [])
                return type("Response", (), {"ok": True, "status_code": 200, "text": ""})()

            def patch_execution(self, execution_id, payload):
                self.patches.append(payload)
                return type("Response", (), {"ok": True, "status_code": 200, "text": ""})()

            def release(self, project_id, intent_id, worker_name):
                self.released.append((project_id, intent_id, worker_name))
                return type("Response", (), {"ok": True, "status_code": 200, "text": ""})()

        env = FakeEnvironment()
        client = FakeClient()
        path = build_report_path(self.handle, "i001", "run_abc")

        explore._write_failure_and_release(
            env,
            self.handle,
            client,
            "proj_001",
            "i001",
            "pi",
            path,
            "run_abc",
            "conclude_parse_failed",
            "invalid JSON",
            execution_id="proj_001_ex001",
        )

        self.assertEqual(client.patches[-1]["status"], "failed")
        self.assertEqual(client.patches[-1]["error_code"], "conclude_parse_failed")
        self.assertIn("invalid JSON", client.patches[-1]["error_detail"])
        self.assertEqual(client.events[-2]["event_type"], "message")
        self.assertEqual(client.events[-2]["role"], "system")
        self.assertIn("dispatcher postprocess failed", client.events[-2]["payload"]["text"])
        self.assertEqual(client.events[-1]["event_type"], "status")
        self.assertEqual(client.events[-1]["payload"]["status"], "failed")
        self.assertEqual(client.events[-1]["payload"]["error_code"], "conclude_parse_failed")
        self.assertEqual(client.released, [("proj_001", "i001", "pi")])


if __name__ == "__main__":
    unittest.main()
